name: Test Python Tree DataStrucutre
on:
    push:
    pull_request:
        branches: [add-tree-python]
    workflow_dispatch:
jobs:
  compile:
    runs-on: ubuntu-latest
    container: python
    
    steps:
      - uses: actions/checkout@v3
      - name: Tests Tree DataStructure Written In Python
        run: |
          pip install pytest
          cd "Data Structures/Python/tests"
          pytest -v 
          
          